services:
  user-srv:
    build:
      target: development
      context: ./backend
      dockerfile: ./apps/user/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db-srv
      - nats
    command: ["pnpm", "run", "dev", "user"]

  todo-list-srv:
    build:
      target: development
      context: ./backend
      dockerfile: ./apps/todo-list/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db-srv
      - nats
    command: ["pnpm", "run", "dev", "todo-list"]

  db-srv:
    image: mongo:7.0.11-jammy
    volumes:
      - db-srv-vol:/data/db

  nats:
    image: nats:2.10.18-alpine3.20

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_ENABLED=false
      - ME_CONFIG_MONGODB_URL=mongodb://db-srv:27017

  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.17
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-srv

volumes:
  pgadmin:
  db-srv-vol:
