services:
  user-srv:
    build:
      target: development
      context: ./backend
      dockerfile: ./apps/user/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - user-db
      - nats
    command: ["pnpm", "run", "dev", "user"]

  user-db:
    image: mongo:7.0.11-jammy
    environment:
      MONGO_INITDB_DATABASE: user_db
    restart: always

    volumes:
      - user-db-vol:/data/db

  nats:
    image: nats:2.10.18-alpine3.20

  nginx:
    container_name: nginx
    image: nginx:stable-alpine3.17
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-srv

volumes:
  pgadmin:
  user-db-vol:
